language: php

notifications:
  on_success: never
  on_failure: change

matrix:
  include:
    - php: '5.6'
      env: WP_VERSION=master WP_MULTISITE=0 PHPLINT=1
    - php: '5.2'
      env: WP_VERSION=master WP_MULTISITE=1 PHPLINT=1
    - php: '5.6'
      env: WP_VERSION=4.1 WP_MULTISITE=1
    - php: '5.5'
      env: WP_VERSION=master WP_MULTISITE=0 CHECKS=1
    - php: '5.5'
      env: WP_VERSION=4.1 WP_MULTISITE=1
    - php: '5.4'
      env: WP_VERSION=4.1 WP_MULTISITE=0
    - php: '5.4'
      env: WP_VERSION=4.1 WP_MULTISITE=1
    - php: '5.5'
      env: WP_VERSION=4.1 WP_MULTISITE=0
    - php: '5.5'
      env: WP_VERSION=4.0 WP_MULTISITE=1
    - php: '5.3'
      env: WP_VERSION=4.0 WP_MULTISITE=0
    - php: '5.4'
      env: WP_VERSION=3.9 WP_MULTISITE=0
    - php: 'hhvm'
      env: WP_VERSION=4.1 WP_MULTISITE=0
    - php: 'hhvm'
      env: WP_VERSION=4.1 WP_MULTISITE=1

before_script:
  - bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION 

script: phpunit
